### ISSUE TITLE
Android 6.0 でクラッシュ

### ISSUE THREAD

**Issue by shts** [shts/KeyakiFeed#13]
パーミション問題...。

```
java.lang.AssertionError: Cannot create parent directories for requested File location
    at com.loopj.android.http.Utils.asserts(Utils.java:39)
    at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:69)
    at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:55)
    at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:45)
    at jp.shts.android.keyakifeed.utils.ImageDownloader$1.<init>(ImageDownloader.java:37)
    at jp.shts.android.keyakifeed.utils.ImageDownloader.createResponseHandler(ImageDownloader.java:37)
    at jp.shts.android.keyakifeed.utils.ImageDownloader.<init>(ImageDownloader.java:31)
    at jp.shts.android.keyakifeed.utils.SimpleImageDownloader.<init>(SimpleImageDownloader.java:20)
    at jp.shts.android.keyakifeed.fragments.BlogFragment$8.<init>(BlogFragment.java:186)
    at jp.shts.android.keyakifeed.fragments.BlogFragment.download(BlogFragment.java:186)
    at jp.shts.android.keyakifeed.fragments.BlogFragment.access$500(BlogFragment.java:37)
    at jp.shts.android.keyakifeed.fragments.BlogFragment$4.onClick(BlogFragment.java:127)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21153)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by shts** [comment]
3f8c4b1c4ca2698b52a1fa4c121ef03724518b53
