### ISSUE TITLE
サムネイル画像の生成

### ISSUE THREAD

**Issue by shts** [shts/KeyakiFeed#8]
ImageMagick を使用して取得した新着記事のサムネイル画像を作成する処理をサーバーに追加する

**Comment by shts** [comment]
```
01-28 03:41:49.495 4365-32448/? E/ActivityManager: Exception thrown launching activities in ProcessRecord{a88b74 21744:jp.shts.android.keyakifeed/u0a224}
                                                   android.os.TransactionTooLargeException: data parcel size 565896 bytes
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:615)
                                                       at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:884)
                                                       at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1309)
                                                       at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:866)
                                                       at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6607)
                                                       at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6671)
                                                       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
                                                       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2794)
                                                       at android.os.Binder.execTransact(Binder.java:565)

```

**Comment by shts** [comment]
https://en-jp.wantedly.com/companies/drivemode/post_articles/40881?source=show-sidebar-recent
http://noizy-radio.blogspot.jp/2013/12/androidbundlestring.html
